# Generated by Django 6.0.5 on 2026-07-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('type', models.CharField(choices=[('film', 'Film'), ('serie', 'Série'), ('documentaire', 'Documentaire')], max_length=20)),
                ('annee_sortie', models.IntegerField()),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('affiche', models.URLField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_gratuit', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus', to='catalogue.categorie')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
